### ISSUE TITLE
"Install vale" link 404s from the marketplace page

### ISSUE THREAD

**Issue by StarfallProjects** [lunaryorn/vscode-vale#14]
This page on VS Code marketplace includes a link to install vale. That link 404s.
https://marketplace.visualstudio.com/items?itemName=lunaryorn.vale
It also fails from within VS Code (search for Vale extension -> Select vale and view the info page -> select Install vale)
It tries to go to: https://valelint.github.io/docs/#installation

However, as far as I can see, that page looks identical to your repository README, and in the README the link works.
It goes to: https://errata-ai.github.io/vale/#installation

**Comment by lunaryorn** [comment]
The link in Readme got fixed after the last release.  The extension page will get fixed when this extension gets released next time.

Don’t known when that’ll be though; don’t have much time for this tbh
