### ISSUE TITLE
Support additional file types (not only markdown)

### ISSUE THREAD

**Issue by TimKam** [lunaryorn/vscode-vale#6]
Vale manages supported file type in the ``.vale`` / ``_vale`` configuration file. Hence, it shouldn't be any problem to remove the current markdown limit (I suppose). I'll take a look and plan to create a PR.

**Comment by lunaryorn** [comment]
@TimKam I'd appreciate a PR to lift the limit if possible.  Note though that the current limit exists to prevent the extension from being loaded for files where it's not used.
